// tslint:disable
export let orderdata: Object[] = [{
    OrderID: 10248,
    CustomerID: "VINET",
    EmployeeID: 1,
    OrderDate: new Date(8364186e5),
    ShipName: "Vins et alcools Chevalier",
    ShipCity: "Reims",
    ShipAddress: "59 rue de l'Abbaye",
    ShipRegion: null,
    ShipPostalCode: "51100",
    ShipCountry: "France",
    Freight: 32.38,
    Verified: !0
}, {
    OrderID: 10249,
    CustomerID: "TOMSP",
    EmployeeID: 2,
    OrderDate: new Date(836505e6),
    ShipName: "Toms Spezialit�ten",
    ShipCity: "M�nster",
    ShipAddress: "Luisenstr. 48",
    ShipRegion: null,
    ShipPostalCode: "44087",
    ShipCountry: "Germany",
    Freight: 11.61,
    Verified: !1
}, {
    OrderID: 10250,
    CustomerID: "HANAR",
    EmployeeID: 3,
    OrderDate: new Date(8367642e5),
    ShipName: "Hanari Carnes",
    ShipCity: "Rio de Janeiro",
    ShipAddress: "Rua do Pa�o, 67",
    ShipRegion: "RJ",
    ShipPostalCode: "05454-876",
    ShipCountry: "Brazil",
    Freight: 65.83,
    Verified: !0
}, {
    OrderID: 10251,
    CustomerID: "VICTE",
    EmployeeID: 4,
    OrderDate: new Date(8367642e5),
    ShipName: "Victuailles en stock",
    ShipCity: "Lyon",
    ShipAddress: "2, rue du Commerce",
    ShipRegion: null,
    ShipPostalCode: "69004",
    ShipCountry: "France",
    Freight: 41.34,
    Verified: !0
}, {
    OrderID: 10252,
    CustomerID: "SUPRD",
    EmployeeID: 5,
    OrderDate: new Date(8368506e5),
    ShipName: "Supr�mes d�lices",
    ShipCity: "Charleroi",
    ShipAddress: "Boulevard Tirou, 255",
    ShipRegion: null,
    ShipPostalCode: "B-6000",
    ShipCountry: "Belgium",
    Freight: 51.3,
    Verified: !0
}, {
    OrderID: 10253,
    CustomerID: "HANAR",
    EmployeeID: 6,
    OrderDate: new Date(836937e6),
    ShipName: "Hanari Carnes",
    ShipCity: "Rio de Janeiro",
    ShipAddress: "Rua do Pa�o, 67",
    ShipRegion: "RJ",
    ShipPostalCode: "05454-876",
    ShipCountry: "Brazil",
    Freight: 58.17,
    Verified: !0
}, {
    OrderID: 10254,
    CustomerID: "CHOPS",
    EmployeeID: 7,
    OrderDate: new Date(8370234e5),
    ShipName: "Chop-suey Chinese",
    ShipCity: "Bern",
    ShipAddress: "Hauptstr. 31",
    ShipRegion: null,
    ShipPostalCode: "3012",
    ShipCountry: "Switzerland",
    Freight: 22.98,
    Verified: !1
}, {
    OrderID: 10255,
    CustomerID: "RICSU",
    EmployeeID: 8,
    OrderDate: new Date(8371098e5),
    ShipName: "Richter Supermarkt",
    ShipCity: "Gen�ve",
    ShipAddress: "Starenweg 5",
    ShipRegion: null,
    ShipPostalCode: "1204",
    ShipCountry: "Switzerland",
    Freight: 148.33,
    Verified: !0
}, {
    OrderID: 10256,
    CustomerID: "WELLI",
    EmployeeID: 9,
    OrderDate: new Date(837369e6),
    ShipName: "Wellington Importadora",
    ShipCity: "Resende",
    ShipAddress: "Rua do Mercado, 12",
    ShipRegion: "SP",
    ShipPostalCode: "08737-363",
    ShipCountry: "Brazil",
    Freight: 13.97,
    Verified: !1
}, {
    OrderID: 10257,
    CustomerID: "HILAA",
    EmployeeID: 10,
    OrderDate: new Date(8374554e5),
    ShipName: "HILARION-Abastos",
    ShipCity: "San Crist�bal",
    ShipAddress: "Carrera 22 con Ave. Carlos Soublette #8-35",
    ShipRegion: "T�chira",
    ShipPostalCode: "5022",
    ShipCountry: "Venezuela",
    Freight: 81.91,
    Verified: !0
}, {
    OrderID: 10258,
    CustomerID: "ERNSH",
    EmployeeID: 11,
    OrderDate: new Date(8375418e5),
    ShipName: "Ernst Handel",
    ShipCity: "Graz",
    ShipAddress: "Kirchgasse 6",
    ShipRegion: null,
    ShipPostalCode: "8010",
    ShipCountry: "Austria",
    Freight: 140.51,
    Verified: !0
}, {
    OrderID: 10259,
    CustomerID: "CENTC",
    EmployeeID: 12,
    OrderDate: new Date(8376282e5),
    ShipName: "Centro comercial Moctezuma",
    ShipCity: "M�xico D.F.",
    ShipAddress: "Sierras de Granada 9993",
    ShipRegion: null,
    ShipPostalCode: "05022",
    ShipCountry: "Mexico",
    Freight: 3.25,
    Verified: !1
}, {
    OrderID: 10260,
    CustomerID: "OTTIK",
    EmployeeID: 13,
    OrderDate: new Date(8377146e5),
    ShipName: "Ottilies K�seladen",
    ShipCity: "K�ln",
    ShipAddress: "Mehrheimerstr. 369",
    ShipRegion: null,
    ShipPostalCode: "50739",
    ShipCountry: "Germany",
    Freight: 55.09,
    Verified: !0
}, {
    OrderID: 10261,
    CustomerID: "QUEDE",
    EmployeeID: 14,
    OrderDate: new Date(8377146e5),
    ShipName: "Que Del�cia",
    ShipCity: "Rio de Janeiro",
    ShipAddress: "Rua da Panificadora, 12",
    ShipRegion: "RJ",
    ShipPostalCode: "02389-673",
    ShipCountry: "Brazil",
    Freight: 3.05,
    Verified: !1
}, {
    OrderID: 10262,
    CustomerID: "RATTC",
    EmployeeID: 15,
    OrderDate: new Date(8379738e5),
    ShipName: "Rattlesnake Canyon Grocery",
    ShipCity: "Albuquerque",
    ShipAddress: "2817 Milton Dr.",
    ShipRegion: "NM",
    ShipPostalCode: "87110",
    ShipCountry: "USA",
    Freight: 48.29,
    Verified: !0
}, {
    OrderID: 10263,
    CustomerID: "ERNSH",
    EmployeeID: 16,
    OrderDate: new Date(8380602e5),
    ShipName: "Ernst Handel",
    ShipCity: "Graz",
    ShipAddress: "Kirchgasse 6",
    ShipRegion: null,
    ShipPostalCode: "8010",
    ShipCountry: "Austria",
    Freight: 146.06,
    Verified: !0
}, {
    OrderID: 10264,
    CustomerID: "FOLKO",
    EmployeeID: 17,
    OrderDate: new Date(8381466e5),
    ShipName: "Folk och f� HB",
    ShipCity: "Br�cke",
    ShipAddress: "�kergatan 24",
    ShipRegion: null,
    ShipPostalCode: "S-844 67",
    ShipCountry: "Sweden",
    Freight: 3.67,
    Verified: !1
}, {
    OrderID: 10265,
    CustomerID: "BLONP",
    EmployeeID: 18,
    OrderDate: new Date(838233e6),
    ShipName: "Blondel p�re et fils",
    ShipCity: "Strasbourg",
    ShipAddress: "24, place Kl�ber",
    ShipRegion: null,
    ShipPostalCode: "67000",
    ShipCountry: "France",
    Freight: 55.28,
    Verified: !0
}, {
    OrderID: 10266,
    CustomerID: "WARTH",
    EmployeeID: 19,
    OrderDate: new Date(8383194e5),
    ShipName: "Wartian Herkku",
    ShipCity: "Oulu",
    ShipAddress: "Torikatu 38",
    ShipRegion: null,
    ShipPostalCode: "90110",
    ShipCountry: "Finland",
    Freight: 25.73,
    Verified: !1
}, {
    OrderID: 10267,
    CustomerID: "FRANK",
    EmployeeID: 20,
    OrderDate: new Date(8385786e5),
    ShipName: "Frankenversand",
    ShipCity: "M�nchen",
    ShipAddress: "Berliner Platz 43",
    ShipRegion: null,
    ShipPostalCode: "80805",
    ShipCountry: "Germany",
    Freight: 208.58,
    Verified: !0
}
];
export let products: Object[] = [
    {
        id: 1,
        name: 'Product A',
        previousYear: 10,
        lastYear: 20
    },
    {
        id: 2,
        name: 'Product B',
        previousYear: 20,
        lastYear: 30
    },
    {
        id: 3,
        name: 'Product C',
        previousYear: 30,
        lastYear: 20
    },
    {
        id: 4,
        name: 'Product D',
        previousYear: 40,
        lastYear: 10
    },
    {
        id: 5,
        name: 'Product E',
        previousYear: 20,
        lastYear: 30
    }
];