export interface PurchaseDetailsArgs {
    ID?: number;
    TransactionID?: string;
    CustomerName?: string;
    Email?: string;
    PurchaseDate?: Date;
    ProductName?: string;
    ProductImage?: string;
    Quantity?: number;
    Amount?: number;
    PaymentMethod?: string;
    Status?: string;
}
export let purchaseDetails: Object[] = [
    {
    ID: 1,
    TransactionID: "TRX202501",
    CustomerName: "Jane Smith",
    Email: "jane.smith@example.com",
    PurchaseDate: new Date("2025-06-20"),
    ProductName: "iMac 24",
    ProductImage: "imac-24.png",
    Quantity: 1,
    Amount: 1199.99,
    PaymentMethod: "Credit Card",
    Status: "Completed"
  },
  {
    ID: 2,
    TransactionID: "TRX202502",
    CustomerName: "Mark Johnson",
    Email: "mark.johnson@example.com",
    PurchaseDate: new Date("2025-06-20"),
    ProductName: "Mac Mini",
    ProductImage: "mac-mini.png",
    Quantity: 3,
    Amount: 1797.00,
    PaymentMethod: "PayPal",
    Status: "Pending"
  },
  {
    ID: 3,
    TransactionID: "TRX202503",
    CustomerName: "Emily White",
    Email: "emily.white@example.com",
    PurchaseDate: new Date("2025-06-20"),
    ProductName: "HomePod Mini",
    ProductImage: "homepod-mini.png",
    Quantity: 6,
    Amount: 594.00,
    PaymentMethod: "Online Transfer",
    Status: "Failed"
  },
  {
    ID: 4,
    TransactionID: "TRX202504",
    CustomerName: "Tom Harris",
    Email: "tom.harris@example.com",
    PurchaseDate: new Date("2025-06-21"),
    ProductName: "iPhone 13",
    ProductImage: "iphone-13.png",
    Quantity: 2,
    Amount: 1399.98,
    PaymentMethod: "Credit Card",
    Status: "Processing"
  },
  {
    ID: 5,
    TransactionID: "TRX202505",
    CustomerName: "Lisa Green",
    Email: "lisa.green@example.com",
    PurchaseDate: new Date("2025-06-21"),
    ProductName: "Apple Watch Series 7",
    ProductImage: "apple-watch-series-7.png",
    Quantity: 4,
    Amount: 1596.00,
    PaymentMethod: "PayPal",
    Status: "Completed"
  },
  {
    ID: 6,
    TransactionID: "TRX202506",
    CustomerName: "Olivia Adams",
    Email: "olivia.adams@example.com",
    PurchaseDate: new Date("2025-06-21"),
    ProductName: "Apple TV 4K",
    ProductImage: "apple-tv-4k.png",
    Quantity: 3,
    Amount: 537.00,
    PaymentMethod: "Cheque",
    Status: "Pending"
  },
  {
    ID: 7,
    TransactionID: "TRX202507",
    CustomerName: "David Clark",
    Email: "david.clark@example.com",
    PurchaseDate: new Date("2025-06-22"),
    ProductName: "iPhone 15 Pro",
    ProductImage: "iphone-15-pro.png",
    Quantity: 1,
    Amount: 999.99,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 8,
    TransactionID: "TRX202508",
    CustomerName: "Rachel Lee",
    Email: "rachel.lee@example.com",
    PurchaseDate: new Date("2025-06-22"),
    ProductName: "MacBook Air M2",
    ProductImage: "macbook-air-m2.png",
    Quantity: 2,
    Amount: 2598.00,
    PaymentMethod: "Credit Card",
    Status: "Completed"
  },
  {
    ID: 9,
    TransactionID: "TRX202509",
    CustomerName: "Lucas Robinson",
    Email: "lucas.robinson@example.com",
    PurchaseDate: new Date("2025-06-22"),
    ProductName: "AirPods Pro",
    ProductImage: "airpods-pro.png",
    Quantity: 6,
    Amount: 1494.00,
    PaymentMethod: "PayPal",
    Status: "Processing"
  },
  {
    ID: 10,
    TransactionID: "TRX202510",
    CustomerName: "Sophia Martinez",
    Email: "sophia.martinez@example.com",
    PurchaseDate: new Date("2025-06-23"),
    ProductName: "iPad Air",
    ProductImage: "ipad-air.png",
    Quantity: 3,
    Amount: 1797.00,
    PaymentMethod: "Online Transfer",
    Status: "Pending"
  },
  {
    ID: 11,
    TransactionID: "TRX202511",
    CustomerName: "Michael Brown",
    Email: "michael.brown@example.com",
    PurchaseDate: new Date("2025-06-23"),
    ProductName: "Apple Watch Series 8",
    ProductImage: "apple-watch-series-8.png",
    Quantity: 4,
    Amount: 1596.00,
    PaymentMethod: "Credit Card",
    Status: "Completed"
  },
  {
    ID: 12,
    TransactionID: "TRX202512",
    CustomerName: "Sarah Davis",
    Email: "sarah.davis@example.com",
    PurchaseDate: new Date("2025-06-23"),
    ProductName: "iPhone 14 Pro Max",
    ProductImage: "iphone-14-pro-max.png",
    Quantity: 1,
    Amount: 1099.99,
    PaymentMethod: "PayPal",
    Status: "Failed"
  },
  {
    ID: 13,
    TransactionID: "TRX202513",
    CustomerName: "James Wilson",
    Email: "james.wilson@example.com",
    PurchaseDate: new Date("2025-06-24"),
    ProductName: "iPhone 15 Plus",
    ProductImage: "iphone-15-plus.png",
    Quantity: 2,
    Amount: 1599.98,
    PaymentMethod: "Online Transfer",
    Status: "Processing"
  },
  {
    ID: 14,
    TransactionID: "TRX202514",
    CustomerName: "Laura Taylor",
    Email: "laura.taylor@example.com",
    PurchaseDate: new Date("2025-06-24"),
    ProductName: "iMac 24",
    ProductImage: "imac-24.png",
    Quantity: 3,
    Amount: 3599.97,
    PaymentMethod: "Credit Card",
    Status: "Completed"
  },
  {
    ID: 15,
    TransactionID: "TRX202515",
    CustomerName: "Chris Evans",
    Email: "chris.evans@example.com",
    PurchaseDate: new Date("2025-06-24"),
    ProductName: "Mac Mini",
    ProductImage: "mac-mini.png",
    Quantity: 4,
    Amount: 2396.00,
    PaymentMethod: "PayPal",
    Status: "Pending"
  },
  {
    ID: 16,
    TransactionID: "TRX202516",
    CustomerName: "Anna Moore",
    Email: "anna.moore@example.com",
    PurchaseDate: new Date("2025-06-25"),
    ProductName: "HomePod Mini",
    ProductImage: "homepod-mini.png",
    Quantity: 7,
    Amount: 693.00,
    PaymentMethod: "Online Transfer",
    Status: "Failed"
  },
  {
    ID: 17,
    TransactionID: "TRX202517",
    CustomerName: "Robert King",
    Email: "robert.king@example.com",
    PurchaseDate: new Date("2025-06-25"),
    ProductName: "iPhone 13",
    ProductImage: "iphone-13.png",
    Quantity: 3,
    Amount: 2099.97,
    PaymentMethod: "Credit Card",
    Status: "Completed"
  },
  {
    ID: 18,
    TransactionID: "TRX202518",
    CustomerName: "Megan Scott",
    Email: "megan.scott@example.com",
    PurchaseDate: new Date("2025-06-25"),
    ProductName: "Apple Watch Series 7",
    ProductImage: "apple-watch-series-7.png",
    Quantity: 2,
    Amount: 798.00,
    PaymentMethod: "PayPal",
    Status: "Processing"
  },
  {
    ID: 19,
    TransactionID: "TRX202519",
    CustomerName: "Daniel Young",
    Email: "daniel.young@example.com",
    PurchaseDate: new Date("2025-06-26"),
    ProductName: "Apple TV 4K",
    ProductImage: "apple-tv-4k.png",
    Quantity: 4,
    Amount: 716.00,
    PaymentMethod: "Online Transfer",
    Status: "Pending"
  },
  {
    ID: 20,
    TransactionID: "TRX202520",
    CustomerName: "Emma Walker",
    Email: "emma.walker@example.com",
    PurchaseDate: new Date("2025-06-26"),
    ProductName: "iPhone 15 Pro",
    ProductImage: "iphone-15-pro.png",
    Quantity: 2,
    Amount: 1999.98,
    PaymentMethod: "Credit Card",
    Status: "Completed"
  },
  {
    ID: 21,
    TransactionID: "TRX202521",
    CustomerName: "Liam Hall",
    Email: "liam.hall@example.com",
    PurchaseDate: new Date("2025-06-26"),
    ProductName: "MacBook Air M2",
    ProductImage: "macbook-air-m2.png",
    Quantity: 1,
    Amount: 1299.00,
    PaymentMethod: "PayPal",
    Status: "Failed"
  },
  {
    ID: 22,
    TransactionID: "TRX202522",
    CustomerName: "Ava Lewis",
    Email: "ava.lewis@example.com",
    PurchaseDate: new Date("2025-06-27"),
    ProductName: "AirPods Pro",
    ProductImage: "airpods-pro.png",
    Quantity: 5,
    Amount: 1245.00,
    PaymentMethod: "Online Transfer",
    Status: "Processing"
  },
  {
    ID: 23,
    TransactionID: "TRX202523",
    CustomerName: "Noah Clark",
    Email: "noah.clark@example.com",
    PurchaseDate: new Date("2025-06-27"),
    ProductName: "iPad Air",
    ProductImage: "ipad-air.png",
    Quantity: 3,
    Amount: 1797.00,
    PaymentMethod: "Credit Card",
    Status: "Completed"
  },
  {
    ID: 24,
    TransactionID: "TRX202524",
    CustomerName: "Mia Turner",
    Email: "mia.turner@example.com",
    PurchaseDate: new Date("2025-06-27"),
    ProductName: "Apple Watch Series 8",
    ProductImage: "apple-watch-series-8.png",
    Quantity: 4,
    Amount: 1596.00,
    PaymentMethod: "PayPal",
    Status: "Pending"
  },
  {
    ID: 25,
    TransactionID: "TRX202525",
    CustomerName: "Ethan Allen",
    Email: "ethan.allen@example.com",
    PurchaseDate: new Date("2025-06-28"),
    ProductName: "iPhone 14 Pro Max",
    ProductImage: "iphone-14-pro-max.png",
    Quantity: 2,
    Amount: 2199.98,
    PaymentMethod: "Online Transfer",
    Status: "Failed"
  },
  {
    ID: 26,
    TransactionID: "TRX202526",
    CustomerName: "Isabella King",
    Email: "isabella.king@example.com",
    PurchaseDate: new Date("2025-06-28"),
    ProductName: "iPhone 15 Plus",
    ProductImage: "iphone-15-plus.png",
    Quantity: 3,
    Amount: 2399.97,
    PaymentMethod: "Credit Card",
    Status: "Completed"
  },
  {
    ID: 27,
    TransactionID: "TRX202527",
    CustomerName: "Jacob Wright",
    Email: "jacob.wright@example.com",
    PurchaseDate: new Date("2025-06-28"),
    ProductName: "iMac 24",
    ProductImage: "imac-24.png",
    Quantity: 1,
    Amount: 1199.99,
    PaymentMethod: "PayPal",
    Status: "Processing"
  },
  {
    ID: 28,
    TransactionID: "TRX202528",
    CustomerName: "Charlotte Lee",
    Email: "charlotte.lee@example.com",
    PurchaseDate: new Date("2025-06-29"),
    ProductName: "Mac Mini",
    ProductImage: "mac-mini.png",
    Quantity: 2,
    Amount: 1198.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 29,
    TransactionID: "TRX202529",
    CustomerName: "William Young",
    Email: "william.young@example.com",
    PurchaseDate: new Date("2025-06-29"),
    ProductName: "HomePod Mini",
    ProductImage: "homepod-mini.png",
    Quantity: 5,
    Amount: 495.00,
    PaymentMethod: "Credit Card",
    Status: "Pending"
  },
  {
    ID: 30,
    TransactionID: "TRX202530",
    CustomerName: "Amelia Harris",
    Email: "amelia.harris@example.com",
    PurchaseDate: new Date("2025-06-29"),
    ProductName: "iPhone 13",
    ProductImage: "iphone-13.png",
    Quantity: 4,
    Amount: 2799.96,
    PaymentMethod: "PayPal",
    Status: "Failed"
  },
  {
    ID: 31,
    TransactionID: "TRX202531",
    CustomerName: "Alexander Scott",
    Email: "alexander.scott@example.com",
    PurchaseDate: new Date("2025-06-30"),
    ProductName: "Apple Watch Series 7",
    ProductImage: "apple-watch-series-7.png",
    Quantity: 3,
    Amount: 1197.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 32,
    TransactionID: "TRX202532",
    CustomerName: "Harper Walker",
    Email: "harper.walker@example.com",
    PurchaseDate: new Date("2025-06-30"),
    ProductName: "Apple TV 4K",
    ProductImage: "apple-tv-4k.png",
    Quantity: 2,
    Amount: 358.00,
    PaymentMethod: "Credit Card",
    Status: "Processing"
  },
  {
    ID: 33,
    TransactionID: "TRX202533",
    CustomerName: "Evelyn Adams",
    Email: "evelyn.adams@example.com",
    PurchaseDate: new Date("2025-06-30"),
    ProductName: "iPhone 15 Pro",
    ProductImage: "iphone-15-pro.png",
    Quantity: 3,
    Amount: 2999.97,
    PaymentMethod: "PayPal",
    Status: "Pending"
  },
  {
    ID: 34,
    TransactionID: "TRX202534",
    CustomerName: "Mason Brown",
    Email: "mason.brown@example.com",
    PurchaseDate: new Date("2025-07-01"),
    ProductName: "MacBook Air M2",
    ProductImage: "macbook-air-m2.png",
    Quantity: 1,
    Amount: 1299.00,
    PaymentMethod: "Online Transfer",
    Status: "Failed"
  },
  {
    ID: 35,
    TransactionID: "TRX202535",
    CustomerName: "Sofia Davis",
    Email: "sofia.davis@example.com",
    PurchaseDate: new Date("2025-07-01"),
    ProductName: "AirPods Pro",
    ProductImage: "airpods-pro.png",
    Quantity: 4,
    Amount: 996.00,
    PaymentMethod: "Credit Card",
    Status: "Completed"
  },
  {
    ID: 36,
    TransactionID: "TRX202536",
    CustomerName: "James Wilson",
    Email: "james.wilson@example.com",
    PurchaseDate: new Date("2025-07-01"),
    ProductName: "iPad Air",
    ProductImage: "ipad-air.png",
    Quantity: 2,
    Amount: 1198.00,
    PaymentMethod: "PayPal",
    Status: "Processing"
  },
  {
    ID: 37,
    TransactionID: "TRX202537",
    CustomerName: "Chloe Taylor",
    Email: "chloe.taylor@example.com",
    PurchaseDate: new Date("2025-07-02"),
    ProductName: "Apple Watch Series 8",
    ProductImage: "apple-watch-series-8.png",
    Quantity: 3,
    Amount: 1197.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 38,
    TransactionID: "TRX202538",
    CustomerName: "Benjamin Lee",
    Email: "benjamin.lee@example.com",
    PurchaseDate: new Date("2025-07-02"),
    ProductName: "iPhone 14 Pro Max",
    ProductImage: "iphone-14-pro-max.png",
    Quantity: 1,
    Amount: 1099.99,
    PaymentMethod: "Credit Card",
    Status: "Pending"
  },
  {
    ID: 39,
    TransactionID: "TRX202539",
    CustomerName: "Zoe Clark",
    Email: "zoe.clark@example.com",
    PurchaseDate: new Date("2025-07-02"),
    ProductName: "iPhone 15 Plus",
    ProductImage: "iphone-15-plus.png",
    Quantity: 4,
    Amount: 3199.96,
    PaymentMethod: "PayPal",
    Status: "Failed"
  },
  {
    ID: 40,
    TransactionID: "TRX202540",
    CustomerName: "Logan Harris",
    Email: "logan.harris@example.com",
    PurchaseDate: new Date("2025-07-03"),
    ProductName: "iMac 24",
    ProductImage: "imac-24.png",
    Quantity: 2,
    Amount: 2399.98,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 41,
    TransactionID: "TRX202541",
    CustomerName: "Ella Young",
    Email: "ella.young@example.com",
    PurchaseDate: new Date("2025-07-03"),
    ProductName: "Mac Mini",
    ProductImage: "mac-mini.png",
    Quantity: 3,
    Amount: 1797.00,
    PaymentMethod: "Credit Card",
    Status: "Processing"
  },
  {
    ID: 42,
    TransactionID: "TRX202542",
    CustomerName: "Lucas Martinez",
    Email: "lucas.martinez@example.com",
    PurchaseDate: new Date("2025-07-03"),
    ProductName: "HomePod Mini",
    ProductImage: "homepod-mini.png",
    Quantity: 6,
    Amount: 594.00,
    PaymentMethod: "PayPal",
    Status: "Pending"
  },
  {
    ID: 43,
    TransactionID: "TRX202543",
    CustomerName: "Aria Walker",
    Email: "aria.walker@example.com",
    PurchaseDate: new Date("2025-07-04"),
    ProductName: "iPhone 13",
    ProductImage: "iphone-13.png",
    Quantity: 1,
    Amount: 699.99,
    PaymentMethod: "Online Transfer",
    Status: "Failed"
  },
  {
    ID: 44,
    TransactionID: "TRX202544",
    CustomerName: "Henry Scott",
    Email: "henry.scott@example.com",
    PurchaseDate: new Date("2025-07-04"),
    ProductName: "Apple Watch Series 7",
    ProductImage: "apple-watch-series-7.png",
    Quantity: 4,
    Amount: 1596.00,
    PaymentMethod: "Credit Card",
    Status: "Completed"
  },
  {
    ID: 45,
    TransactionID: "TRX202545",
    CustomerName: "Lily Adams",
    Email: "lily.adams@example.com",
    PurchaseDate: new Date("2025-07-04"),
    ProductName: "Apple TV 4K",
    ProductImage: "apple-tv-4k.png",
    Quantity: 3,
    Amount: 537.00,
    PaymentMethod: "PayPal",
    Status: "Processing"
  },
  {
    ID: 46,
    TransactionID: "TRX202546",
    CustomerName: "Jack Wilson",
    Email: "jack.wilson@example.com",
    PurchaseDate: new Date("2025-07-05"),
    ProductName: "iPhone 15 Pro",
    ProductImage: "iphone-15-pro.png",
    Quantity: 2,
    Amount: 1999.98,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 47,
    TransactionID: "TRX202547",
    CustomerName: "Grace Brown",
    Email: "grace.brown@example.com",
    PurchaseDate: new Date("2025-07-05"),
    ProductName: "MacBook Air M2",
    ProductImage: "macbook-air-m2.png",
    Quantity: 1,
    Amount: 1299.00,
    PaymentMethod: "Credit Card",
    Status: "Pending"
  },
  {
    ID: 48,
    TransactionID: "TRX202548",
    CustomerName: "Owen Davis",
    Email: "owen.davis@example.com",
    PurchaseDate: new Date("2025-07-05"),
    ProductName: "AirPods Pro",
    ProductImage: "airpods-pro.png",
    Quantity: 10,
    Amount: 1743.00,
    PaymentMethod: "PayPal",
    Status: "Failed"
  },
  {
    ID: 49,
    TransactionID: "TRX202549",
    CustomerName: "Hannah Lee",
    Email: "hannah.lee@example.com",
    PurchaseDate: new Date("2025-07-06"),
    ProductName: "iPad Air",
    ProductImage: "ipad-air.png",
    Quantity: 4,
    Amount: 2396.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 50,
    TransactionID: "TRX202550",
    CustomerName: "Elijah Clark",
    Email: "elijah.clark@example.com",
    PurchaseDate: new Date("2025-07-06"),
    ProductName: "Apple Watch Series 8",
    ProductImage: "apple-watch-series-8.png",
    Quantity: 2,
    Amount: 798.00,
    PaymentMethod: "Credit Card",
    Status: "Processing"
  },
  {
    ID: 51,
    TransactionID: "TRX202551",
    CustomerName: "Sophie Turner",
    Email: "sophie.turner@example.com",
    PurchaseDate: new Date("2025-07-06"),
    ProductName: "iPhone 14 Pro Max",
    ProductImage: "iphone-14-pro-max.png",
    Quantity: 3,
    Amount: 3299.97,
    PaymentMethod: "PayPal",
    Status: "Pending"
  },
  {
    ID: 52,
    TransactionID: "TRX202552",
    CustomerName: "Daniel Harris",
    Email: "daniel.harris@example.com",
    PurchaseDate: new Date("2025-07-07"),
    ProductName: "iPhone 15 Plus",
    ProductImage: "iphone-15-plus.png",
    Quantity: 1,
    Amount: 799.99,
    PaymentMethod: "Online Transfer",
    Status: "Failed"
  },
  {
    ID: 53,
    TransactionID: "TRX202553",
    CustomerName: "Avery Wright",
    Email: "avery.wright@example.com",
    PurchaseDate: new Date("2025-07-07"),
    ProductName: "iMac 24",
    ProductImage: "imac-24.png",
    Quantity: 4,
    Amount: 4799.96,
    PaymentMethod: "Credit Card",
    Status: "Completed"
  },
  {
    ID: 54,
    TransactionID: "TRX202554",
    CustomerName: "Scarlett Young",
    Email: "scarlett.young@example.com",
    PurchaseDate: new Date("2025-07-07"),
    ProductName: "Mac Mini",
    ProductImage: "mac-mini.png",
    Quantity: 3,
    Amount: 1797.00,
    PaymentMethod: "PayPal",
    Status: "Processing"
  },
  {
    ID: 55,
    TransactionID: "TRX202555",
    CustomerName: "Mason Adams",
    Email: "mason.adams@example.com",
    PurchaseDate: new Date("2025-07-08"),
    ProductName: "HomePod Mini",
    ProductImage: "homepod-mini.png",
    Quantity: 6,
    Amount: 594.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 56,
    TransactionID: "TRX202556",
    CustomerName: "Luna Scott",
    Email: "luna.scott@example.com",
    PurchaseDate: new Date("2025-07-08"),
    ProductName: "iPhone 13",
    ProductImage: "iphone-13.png",
    Quantity: 2,
    Amount: 1399.98,
    PaymentMethod: "Credit Card",
    Status: "Pending"
  },
  {
    ID: 57,
    TransactionID: "TRX202557",
    CustomerName: "Ethan Brown",
    Email: "ethan.brown@example.com",
    PurchaseDate: new Date("2025-07-08"),
    ProductName: "Apple Watch Series 7",
    ProductImage: "apple-watch-series-7.png",
    Quantity: 4,
    Amount: 1596.00,
    PaymentMethod: "PayPal",
    Status: "Failed"
  },
  {
    ID: 58,
    TransactionID: "TRX202558",
    CustomerName: "Zoe Davis",
    Email: "zoe.davis@example.com",
    PurchaseDate: new Date("2025-07-09"),
    ProductName: "Apple TV 4K",
    ProductImage: "apple-tv-4k.png",
    Quantity: 3,
    Amount: 537.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 59,
    TransactionID: "TRX202559",
    CustomerName: "Logan Wilson",
    Email: "logan.wilson@example.com",
    PurchaseDate: new Date("2025-07-09"),
    ProductName: "iPhone 15 Pro",
    ProductImage: "iphone-15-pro.png",
    Quantity: 1,
    Amount: 999.99,
    PaymentMethod: "Credit Card",
    Status: "Processing"
  },
  {
    ID: 60,
    TransactionID: "TRX202560",
    CustomerName: "Aria Lee",
    Email: "aria.lee@example.com",
    PurchaseDate: new Date("2025-07-09"),
    ProductName: "MacBook Air M2",
    ProductImage: "macbook-air-m2.png",
    Quantity: 2,
    Amount: 2598.00,
    PaymentMethod: "PayPal",
    Status: "Pending"
  },
  {
    ID: 61,
    TransactionID: "TRX202561",
    CustomerName: "Lucas Clark",
    Email: "lucas.clark@example.com",
    PurchaseDate: new Date("2025-07-10"),
    ProductName: "AirPods Pro",
    ProductImage: "airpods-pro.png",
    Quantity: 5,
    Amount: 1245.00,
    PaymentMethod: "Online Transfer",
    Status: "Failed"
  },
  {
    ID: 62,
    TransactionID: "TRX202562",
    CustomerName: "Ella Harris",
    Email: "ella.harris@example.com",
    PurchaseDate: new Date("2025-07-10"),
    ProductName: "iPad Air",
    ProductImage: "ipad-air.png",
    Quantity: 3,
    Amount: 1797.00,
    PaymentMethod: "Credit Card",
    Status: "Completed"
  },
  {
    ID: 63,
    TransactionID: "TRX202563",
    CustomerName: "Noah Young",
    Email: "noah.young@example.com",
    PurchaseDate: new Date("2025-07-10"),
    ProductName: "Apple Watch Series 8",
    ProductImage: "apple-watch-series-8.png",
    Quantity: 4,
    Amount: 1596.00,
    PaymentMethod: "PayPal",
    Status: "Processing"
  },
  {
    ID: 64,
    TransactionID: "TRX202564",
    CustomerName: "Mia Scott",
    Email: "mia.scott@example.com",
    PurchaseDate: new Date("2025-07-11"),
    ProductName: "iPhone 14 Pro Max",
    ProductImage: "iphone-14-pro-max.png",
    Quantity: 2,
    Amount: 2199.98,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 65,
    TransactionID: "TRX202565",
    CustomerName: "Liam Turner",
    Email: "liam.turner@example.com",
    PurchaseDate: new Date("2025-07-11"),
    ProductName: "iPhone 15 Plus",
    ProductImage: "iphone-15-plus.png",
    Quantity: 3,
    Amount: 2399.97,
    PaymentMethod: "Credit Card",
    Status: "Pending"
  },
  {
    ID: 66,
    TransactionID: "TRX202566",
    CustomerName: "Ava Brown",
    Email: "ava.brown@example.com",
    PurchaseDate: new Date("2025-07-11"),
    ProductName: "iMac 24",
    ProductImage: "imac-24.png",
    Quantity: 1,
    Amount: 1199.99,
    PaymentMethod: "PayPal",
    Status: "Failed"
  },
  {
    ID: 67,
    TransactionID: "TRX202567",
    CustomerName: "Elijah Davis",
    Email: "elijah.davis@example.com",
    PurchaseDate: new Date("2025-07-12"),
    ProductName: "Mac Mini",
    ProductImage: "mac-mini.png",
    Quantity: 4,
    Amount: 2396.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 68,
    TransactionID: "TRX202568",
    CustomerName: "Sophie Wilson",
    Email: "sophie.wilson@example.com",
    PurchaseDate: new Date("2025-07-12"),
    ProductName: "HomePod Mini",
    ProductImage: "homepod-mini.png",
    Quantity: 7,
    Amount: 693.00,
    PaymentMethod: "Credit Card",
    Status: "Processing"
  },
  {
    ID: 69,
    TransactionID: "TRX202569",
    CustomerName: "Daniel Lee",
    Email: "daniel.lee@example.com",
    PurchaseDate: new Date("2025-07-12"),
    ProductName: "iPhone 13",
    ProductImage: "iphone-13.png",
    Quantity: 3,
    Amount: 2099.97,
    PaymentMethod: "PayPal",
    Status: "Pending"
  },
  {
    ID: 70,
    TransactionID: "TRX202570",
    CustomerName: "Avery Clark",
    Email: "avery.clark@example.com",
    PurchaseDate: new Date("2025-07-13"),
    ProductName: "Apple Watch Series 7",
    ProductImage: "apple-watch-series-7.png",
    Quantity: 2,
    Amount: 798.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 71,
    TransactionID: "TRX202571",
    CustomerName: "Scarlett Harris",
    Email: "scarlett.harris@example.com",
    PurchaseDate: new Date("2025-07-13"),
    ProductName: "Apple TV 4K",
    ProductImage: "apple-tv-4k.png",
    Quantity: 4,
    Amount: 716.00,
    PaymentMethod: "Credit Card",
    Status: "Failed"
  },
  {
    ID: 72,
    TransactionID: "TRX202572",
    CustomerName: "Mason Young",
    Email: "mason.young@example.com",
    PurchaseDate: new Date("2025-07-13"),
    ProductName: "iPhone 15 Pro",
    ProductImage: "iphone-15-pro.png",
    Quantity: 3,
    Amount: 2999.97,
    PaymentMethod: "PayPal",
    Status: "Processing"
  },
  {
    ID: 73,
    TransactionID: "TRX202573",
    CustomerName: "Luna Scott",
    Email: "luna.scott@example.com",
    PurchaseDate: new Date("2025-07-14"),
    ProductName: "MacBook Air M2",
    ProductImage: "macbook-air-m2.png",
    Quantity: 1,
    Amount: 1299.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 74,
    TransactionID: "TRX202574",
    CustomerName: "Ethan Turner",
    Email: "ethan.turner@example.com",
    PurchaseDate: new Date("2025-07-14"),
    ProductName: "AirPods Pro",
    ProductImage: "airpods-pro.png",
    Quantity: 6,
    Amount: 1494.00,
    PaymentMethod: "Credit Card",
    Status: "Pending"
  },
  {
    ID: 75,
    TransactionID: "TRX202575",
    CustomerName: "Zoe Brown",
    Email: "zoe.brown@example.com",
    PurchaseDate: new Date("2025-07-14"),
    ProductName: "iPad Air",
    ProductImage: "ipad-air.png",
    Quantity: 2,
    Amount: 1198.00,
    PaymentMethod: "PayPal",
    Status: "Failed"
  },
  {
    ID: 76,
    TransactionID: "TRX202576",
    CustomerName: "Logan Davis",
    Email: "logan.davis@example.com",
    PurchaseDate: new Date("2025-07-15"),
    ProductName: "Apple Watch Series 8",
    ProductImage: "apple-watch-series-8.png",
    Quantity: 3,
    Amount: 1197.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 77,
    TransactionID: "TRX202577",
    CustomerName: "Ella Wilson",
    Email: "ella.wilson@example.com",
    PurchaseDate: new Date("2025-07-15"),
    ProductName: "iPhone 14 Pro Max",
    ProductImage: "iphone-14-pro-max.png",
    Quantity: 1,
    Amount: 1099.99,
    PaymentMethod: "Credit Card",
    Status: "Processing"
  },
  {
    ID: 78,
    TransactionID: "TRX202578",
    CustomerName: "Noah Lee",
    Email: "noah.lee@example.com",
    PurchaseDate: new Date("2025-07-15"),
    ProductName: "iPhone 15 Plus",
    ProductImage: "iphone-15-plus.png",
    Quantity: 4,
    Amount: 3199.96,
    PaymentMethod: "PayPal",
    Status: "Pending"
  },
  {
    ID: 79,
    TransactionID: "TRX202579",
    CustomerName: "Mia Clark",
    Email: "mia.clark@example.com",
    PurchaseDate: new Date("2025-07-16"),
    ProductName: "iMac 24",
    ProductImage: "imac-24.png",
    Quantity: 2,
    Amount: 2399.98,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 80,
    TransactionID: "TRX202580",
    CustomerName: "Liam Harris",
    Email: "liam.harris@example.com",
    PurchaseDate: new Date("2025-07-16"),
    ProductName: "Mac Mini",
    ProductImage: "mac-mini.png",
    Quantity: 3,
    Amount: 1797.00,
    PaymentMethod: "Credit Card",
    Status: "Failed"
  },
  {
    ID: 81,
    TransactionID: "TRX202581",
    CustomerName: "Ava Scott",
    Email: "ava.scott@example.com",
    PurchaseDate: new Date("2025-07-16"),
    ProductName: "HomePod Mini",
    ProductImage: "homepod-mini.png",
    Quantity: 5,
    Amount: 495.00,
    PaymentMethod: "PayPal",
    Status: "Processing"
  },
  {
    ID: 82,
    TransactionID: "TRX202582",
    CustomerName: "Elijah Young",
    Email: "elijah.young@example.com",
    PurchaseDate: new Date("2025-07-17"),
    ProductName: "iPhone 13",
    ProductImage: "iphone-13.png",
    Quantity: 4,
    Amount: 2799.96,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 83,
    TransactionID: "TRX202583",
    CustomerName: "Sophie Brown",
    Email: "sophie.brown@example.com",
    PurchaseDate: new Date("2025-07-17"),
    ProductName: "Apple Watch Series 7",
    ProductImage: "apple-watch-series-7.png",
    Quantity: 3,
    Amount: 1197.00,
    PaymentMethod: "Credit Card",
    Status: "Pending"
  },
  {
    ID: 84,
    TransactionID: "TRX202584",
    CustomerName: "Daniel Turner",
    Email: "daniel.turner@example.com",
    PurchaseDate: new Date("2025-07-17"),
    ProductName: "Apple TV 4K",
    ProductImage: "apple-tv-4k.png",
    Quantity: 2,
    Amount: 358.00,
    PaymentMethod: "PayPal",
    Status: "Failed"
  },
  {
    ID: 85,
    TransactionID: "TRX202585",
    CustomerName: "Avery Wilson",
    Email: "avery.wilson@example.com",
    PurchaseDate: new Date("2025-07-18"),
    ProductName: "iPhone 15 Pro",
    ProductImage: "iphone-15-pro.png",
    Quantity: 4,
    Amount: 3999.96,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 86,
    TransactionID: "TRX202586",
    CustomerName: "Scarlett Clark",
    Email: "scarlett.clark@example.com",
    PurchaseDate: new Date("2025-07-18"),
    ProductName: "MacBook Air M2",
    ProductImage: "macbook-air-m2.png",
    Quantity: 2,
    Amount: 2598.00,
    PaymentMethod: "Credit Card",
    Status: "Processing"
  },
  {
    ID: 87,
    TransactionID: "TRX202587",
    CustomerName: "Mason Lee",
    Email: "mason.lee@example.com",
    PurchaseDate: new Date("2025-07-18"),
    ProductName: "AirPods Pro",
    ProductImage: "airpods-pro.png",
    Quantity: 6,
    Amount: 1494.00,
    PaymentMethod: "PayPal",
    Status: "Pending"
  },
  {
    ID: 88,
    TransactionID: "TRX202588",
    CustomerName: "Luna Harris",
    Email: "luna.harris@example.com",
    PurchaseDate: new Date("2025-07-19"),
    ProductName: "iPad Air",
    ProductImage: "ipad-air.png",
    Quantity: 3,
    Amount: 1797.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 89,
    TransactionID: "TRX202589",
    CustomerName: "Ethan Scott",
    Email: "ethan.scott@example.com",
    PurchaseDate: new Date("2025-07-19"),
    ProductName: "Apple Watch Series 8",
    ProductImage: "apple-watch-series-8.png",
    Quantity: 4,
    Amount: 1596.00,
    PaymentMethod: "Credit Card",
    Status: "Failed"
  },
  {
    ID: 90,
    TransactionID: "TRX202590",
    CustomerName: "Zoe Young",
    Email: "zoe.young@example.com",
    PurchaseDate: new Date("2025-07-19"),
    ProductName: "iPhone 14 Pro Max",
    ProductImage: "iphone-14-pro-max.png",
    Quantity: 2,
    Amount: 2199.98,
    PaymentMethod: "PayPal",
    Status: "Processing"
  },
  {
    ID: 91,
    TransactionID: "TRX202591",
    CustomerName: "Logan Brown",
    Email: "logan.brown@example.com",
    PurchaseDate: new Date("2025-07-20"),
    ProductName: "iPhone 15 Plus",
    ProductImage: "iphone-15-plus.png",
    Quantity: 3,
    Amount: 2399.97,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 92,
    TransactionID: "TRX202592",
    CustomerName: "Ella Davis",
    Email: "ella.davis@example.com",
    PurchaseDate: new Date("2025-07-20"),
    ProductName: "iMac 24",
    ProductImage: "imac-24.png",
    Quantity: 1,
    Amount: 1199.99,
    PaymentMethod: "Credit Card",
    Status: "Pending"
  },
  {
    ID: 93,
    TransactionID: "TRX202593",
    CustomerName: "Noah Wilson",
    Email: "noah.wilson@example.com",
    PurchaseDate: new Date("2025-07-20"),
    ProductName: "Mac Mini",
    ProductImage: "mac-mini.png",
    Quantity: 2,
    Amount: 1198.00,
    PaymentMethod: "PayPal",
    Status: "Failed"
  },
  {
    ID: 94,
    TransactionID: "TRX202594",
    CustomerName: "Mia Lee",
    Email: "mia.lee@example.com",
    PurchaseDate: new Date("2025-08-01"),
    ProductName: "HomePod Mini",
    ProductImage: "homepod-mini.png",
    Quantity: 6,
    Amount: 594.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 95,
    TransactionID: "TRX202595",
    CustomerName: "Liam Clark",
    Email: "liam.clark@example.com",
    PurchaseDate: new Date("2025-08-01"),
    ProductName: "iPhone 13",
    ProductImage: "iphone-13.png",
    Quantity: 3,
    Amount: 2099.97,
    PaymentMethod: "Credit Card",
    Status: "Processing"
  },
  {
    ID: 96,
    TransactionID: "TRX202596",
    CustomerName: "Ava Harris",
    Email: "ava.harris@example.com",
    PurchaseDate: new Date("2025-08-01"),
    ProductName: "Apple Watch Series 7",
    ProductImage: "apple-watch-series-7.png",
    Quantity: 4,
    Amount: 1596.00,
    PaymentMethod: "PayPal",
    Status: "Pending"
  },
  {
    ID: 97,
    TransactionID: "TRX202597",
    CustomerName: "Elijah Scott",
    Email: "elijah.scott@example.com",
    PurchaseDate: new Date("2025-08-02"),
    ProductName: "Apple TV 4K",
    ProductImage: "apple-tv-4k.png",
    Quantity: 3,
    Amount: 537.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  },
  {
    ID: 98,
    TransactionID: "TRX202598",
    CustomerName: "Sophie Young",
    Email: "sophie.young@example.com",
    PurchaseDate: new Date("2025-08-02"),
    ProductName: "iPhone 15 Pro",
    ProductImage: "iphone-15-pro.png",
    Quantity: 2,
    Amount: 1999.98,
    PaymentMethod: "Credit Card",
    Status: "Failed"
  },
  {
    ID: 99,
    TransactionID: "TRX202599",
    CustomerName: "Daniel Brown",
    Email: "daniel.brown@example.com",
    PurchaseDate: new Date("2025-08-02"),
    ProductName: "MacBook Air M2",
    ProductImage: "macbook-air-m2.png",
    Quantity: 1,
    Amount: 1299.00,
    PaymentMethod: "PayPal",
    Status: "Processing"
  },
  {
    ID: 100,
    TransactionID: "TRX2025100",
    CustomerName: "Avery Turner",
    Email: "avery.turner@example.com",
    PurchaseDate: new Date("2025-08-03"),
    ProductName: "AirPods Pro",
    ProductImage: "airpods-pro.png",
    Quantity: 7,
    Amount: 1743.00,
    PaymentMethod: "Online Transfer",
    Status: "Completed"
  }
];