
/**
 * Chart datasource
 */


export let employeeData: Object[] = [{
    'EmployeeID': 1,
    'yValue': 2,
    'FirstName': 'Nancy',
    'Title': 'Sales Representative',
    'HireDate': new Date(1992, 0, 1),
},
{
    'EmployeeID': 2,
    'yValue': 5,
    'FirstName': 'Andrew',
    'Title': 'Vice President, Sales',
    'HireDate': new Date(1992, 1, 1),
},
{
    'EmployeeID': 3,
    'yValue': 8,
    'FirstName': 'Janet',
    'Title': 'Sales Representative',
    'HireDate': new Date(1992, 2, 1),
},
{
    'EmployeeID': 4,
    'yValue': 4,
    'FirstName': 'Margaret',
    'Title': 'Sales Representative',
    'HireDate': new Date(1992, 3, 1),
},
{
    'EmployeeID': 5,
    'yValue': 7,
    'FirstName': 'Steven',
    'Title': 'Sales Manager',
    'HireDate': new Date(1992, 4, 1),
},
{
    'EmployeeID': 6,
    'yValue': 9,
    'FirstName': 'Michael',
    'Title': 'Sales Representative',
    'HireDate': new Date(1992, 5, 1),
},
{
    'EmployeeID': 7,
    'yValue': 6,
    'FirstName': 'Robert',
    'Title': 'Sales Representative',
    'HireDate': new Date(1992, 6, 1),
},
{
    'EmployeeID': 8,
    'yValue': 4,
    'FirstName': 'Laura',
    'Title': 'Inside Sales Coordinator',
    'HireDate': new Date(1992, 7, 1),
},
{
    'EmployeeID': 9,
    'yValue': 8,
    'FirstName': 'Anne',
    'Title': 'Sales Representative',
    'HireDate': new Date(1992, 8, 1),
}, {
    'EmployeeID': 10,
    'yValue': 2,
    'FirstName': 'Fletcher',
    'Title': 'Sales Representative',
    'HireDate': new Date(1992, 9, 1),
},
{
    'EmployeeID': 11,
    'yValue': 5,
    'FirstName': 'Robin',
    'Title': 'Vice President, Sales',
    'HireDate': new Date(1992, 10, 1),
},
{
    'EmployeeID': 12,
    'yValue': 8,
    'FirstName': 'Mathew',
    'Title': 'Sales Representative',
    'HireDate': new Date(1992, 11, 1),
},
{
    'EmployeeID': 13,
    'yValue': 4,
    'FirstName': 'Henry',
    'Title': 'Sales Representative',
    'HireDate': new Date(1993, 0, 1),
},
{
    'EmployeeID': 14,
    'yValue': 7,
    'FirstName': 'Flemming',
    'Title': 'Sales Manager',
    'HireDate': new Date(1993, 1, 1),
},
{
    'EmployeeID': 15,
    'yValue': 9,
    'FirstName': 'Clarke',
    'Title': 'Sales Representative',
    'HireDate': new Date(1993, 2, 1),
},
{
    'EmployeeID': 16,
    'yValue': 6,
    'FirstName': 'Martin',
    'Title': 'Sales Representative',
    'HireDate': new Date(1993, 3, 1),
},
{
    'EmployeeID': 17,
    'yValue': 4,
    'FirstName': 'Loius',
    'Title': 'Inside Sales Coordinator',
    'HireDate': new Date(1993, 4, 1),
},
{
    'EmployeeID': 18,
    'yValue': 8,
    'FirstName': 'Arthur',
    'Title': 'Sales Representative',
    'HireDate': new Date(1993, 5, 1),
},
{
    'EmployeeID': 19,
    'yValue': 5,
    'FirstName': 'Marcus',
    'Title': 'Sales Representative',
    'HireDate': new Date(1993, 6, 1),
},
{
    'EmployeeID': 20,
    'yValue': 7,
    'FirstName': 'Albert',
    'Title': 'Inside Sales Coordinator',
    'HireDate': new Date(1993, 7, 1),
},
{
    'EmployeeID': 21,
    'yValue': 9,
    'FirstName': 'Nicolas',
    'Title': 'Inside Sales Coordinator',
    'HireDate': new Date(1993, 8, 1),
},
{
    'EmployeeID': 22,
    'yValue': 7,
    'FirstName': 'Behardien',
    'Title': 'Sales Representative',
    'HireDate': new Date(1993, 9, 1),
},
{
    'EmployeeID': 23,
    'yValue': 3,
    'FirstName': 'Bruce',
    'Title': 'Inside Sales Coordinator',
    'HireDate': new Date(1993, 10, 1),
},
{
    'EmployeeID': 24,
    'yValue': 7,
    'FirstName': 'Kimi',
    'Title': 'Inside Sales Coordinator',
    'HireDate': new Date(1993, 11, 1),
}];
